<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>PassTheStick.Guest</RootNamespace>
    <AssemblyName>PassTheStick.Guest</AssemblyName>
    <Version>0.1.29</Version>
    <AssemblyVersion>0.1.29.0</AssemblyVersion>
    <FileVersion>0.1.29.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PassTheStick.Shared\PassTheStick.Shared.csproj" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
  </ItemGroup>

</Project>
