<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PassTheStick.Shared</AssemblyName>
    <RootNamespace>PassTheStick.Shared</RootNamespace>
  </PropertyGroup>

</Project>
