<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\assets\passthestick.ico</ApplicationIcon>
    <Version>0.1.25</Version>
    <AssemblyVersion>0.1.25.0</AssemblyVersion>
    <FileVersion>0.1.25.0</FileVersion>
    <AssemblyName>PassTheStick</AssemblyName>
    <RootNamespace>PassTheStick.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PassTheStick.Guest\PassTheStick.Guest.csproj" />
    <ProjectReference Include="..\PassTheStick.Shared\PassTheStick.Shared.csproj" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="Nefarius.Drivers.HidHide" Version="3.3.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\NEWLOGO.png" Link="appicon.png" />
    <Resource Include="..\..\assets\passthestick.ico" Link="passthestick.ico" />
  </ItemGroup>

</Project>
